name: Environment variables # ワークフロー名

on: [push] # イベント(プッシュ時に起動)

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: main #ジョブレベルで環境変数を参照
    steps:
      # シェルコマンドからジョブレベルの環境変数を参照
      - run: echo "${BRANCH}"
      - uses: actions/checkout@v4
        with:
          ref: ${{env.BRANCH}}