name: Manual # ワークフロー名

on:
  workflow_dispatch: # 手動実行イベント
    inputs:
      greeting: # 入力パラメータ名
        type: choice
        options:
          -info
          -warn
          -error

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # 入力パラメータ「greeting」の値を標準出力に出力
      - run: echo "${{ inputs.greeting }}"